package com.interviewprep.interviewservice.entity;

import jakarta.persistence.*;
import lombok.*;
import java.time.LocalDateTime;

/**
 * Day 13 – Pre-generated Question Bank.
 *
 * Stores questions generated by the background @Scheduled job.
 * InterviewService pulls 60% of questions from here for performance,
 * supplementing with 40% fresh AI generation.
 */
@Entity
@Table(name = "question_bank", indexes = {
        @Index(name = "idx_qb_role_level", columnList = "role,level,type"),
        @Index(name = "idx_qb_role", columnList = "role")
})
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class QuestionBank {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false)
    private String role;

    @Column(nullable = false)
    private String level; // easy | medium | hard

    @Column(nullable = false)
    private String type; // subjective | mcq | coding

    @Column(columnDefinition = "TEXT", nullable = false)
    private String questionText;

    /** For MCQ: correct answer letter (A/B/C/D). */
    private String correctAnswer;

    /** For MCQ: JSON array of option strings. */
    @Column(columnDefinition = "TEXT")
    private String options;

    /** Topic tag for weak-topic targeting. */
    private String topic;

    /** Times this question has been used in sessions. */
    @Builder.Default
    private int usageCount = 0;

    @Builder.Default
    private LocalDateTime createdAt = LocalDateTime.now();
}
