package com.interviewprep.interviewservice.entity;

import jakarta.persistence.*;
import lombok.*;

/**
 * Stores a single interview question tied to a session.
 * Generated by Flask/Ollama and persisted for later evaluation.
 */
@Entity
@Table(name = "questions")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Question {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** The session this question belongs to. */
    @Column(nullable = false)
    private Long sessionId;

    /** The question text. */
    @Column(nullable = false, columnDefinition = "TEXT")
    private String questionText;

    /** subjective | mcq | coding */
    @Column(nullable = false)
    private String type;

    /**
     * Correct answer (used for MCQ auto-scoring).
     * For subjective/coding, this holds the expected output / model answer.
     */
    @Column(columnDefinition = "TEXT")
    private String correctAnswer;

    /** MCQ options stored as JSON string (for MCQ type). */
    @Column(columnDefinition = "TEXT")
    private String options;

    /** Explanation for the correct answer (MCQ). */
    @Column(columnDefinition = "TEXT")
    private String explanation;

    /** Order of the question in the session (1-based). */
    private Integer questionOrder;

    /**
     * Day 9 – Topic this question covers (e.g., "OOP", "Collections", "Threading").
     * Used for weak-topic detection and adaptive question generation.
     */
    private String topic;
}
